#!/usr/bin/with-contenv bash

cd /config

chown -R ${PUID}:${PGID} \
    /config \
    /app

if [ ! -f /config/config.env ]; then
    s6-setuidgid ${PUID}:${PGID} /app/onelist -run config
    s6-setuidgid ${PUID}:${PGID} /app/onelist -run admin
fi
